# Spam or Ham

In [1]:
#import Library
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('spam.csv',encoding='latin-1')

In [3]:
df

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [4]:
# dropping the column
df.drop(['Unnamed: 2','Unnamed: 3','Unnamed: 4'],axis=1,inplace=True)

In [5]:
df

v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [6]:
# rename the columns
df = df.rename(columns={'v1': 'Label', 'v2': 'Message'})

In [7]:
df

Label                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [8]:
# Target variable 'label' is categorical,convert it into numeric value
df['label_num'] = df.Label.map({'ham': 0,'spam':1})

In [28]:
df.head()

Label                                            Message  label_num
0   ham  Go until jurong point, crazy.. Available only ...          0
1   ham                      Ok lar... Joking wif u oni...          0
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...          1
3   ham  U dun say so early hor... U c already then say...          0
4   ham  Nah I don't think he goes to usf, he lives aro...          0

In [9]:
df.Label.value_counts()

ham     4825
spam     747
Name: Label, dtype: int64

In [10]:
# define X and Y datasets  from 'data'
X = df.Message
y = df.Label

In [11]:
print(X.shape)
print(y.shape)

(5572,)
(5572,)


In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=7)

In [13]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(4179,)
(4179,)
(1393,)
(1393,)


In [14]:
# call the vectorizer
from sklearn.feature_extraction.text import CountVectorizer
toNumeric = CountVectorizer()

In [15]:
# create vocabulary and create document-term matrix
toNumeric.fit(X_train) ## Create vocabulary
X_train_dtm = toNumeric.transform(X_train)

In [16]:
X_test_dtm = toNumeric.transform(X_test)
X_test_dtm

<1393x7496 sparse matrix of type '<class 'numpy.int64'>'
	with 17176 stored elements in Compressed Sparse Row format>

In [17]:
#Building and evaluate a model

In [18]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()

In [19]:
nb.fit(X_train_dtm,y_train)

MultinomialNB()

In [20]:
y_pred_class = nb.predict(X_test_dtm)

In [21]:
# Accuracy calculation
from sklearn import metrics

In [22]:
nb.score(X_test_dtm,y_test)

0.9870782483847811

In [23]:
metrics.accuracy_score(y_test,y_pred_class)

0.9870782483847811

In [24]:
metrics.confusion_matrix(y_test,y_pred_class)

array([[1208,    3],
       [  15,  167]], dtype=int64)

In [25]:
#predict probability for test data instead of labels directly
y_pred_prob = nb.predict_proba(X_test_dtm)[:,1]
y_pred_prob

array([5.78296750e-06, 2.72677694e-03, 2.28801281e-05, ...,
       7.76200808e-06, 1.54240695e-04, 5.27530953e-07])

In [26]:
# calculate AUC _ ROC 
metrics.roc_auc_score(y_test,y_pred_prob)

0.9811163238083139

In [29]:
#Compare multiple models

In [30]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

In [31]:
lr.fit(X_train_dtm,y_train)

LogisticRegression()

In [32]:
lr.score(X_test_dtm,y_test)

0.9834888729361091

In [33]:
# calculate predicted probability for x_test_dtm
y_pred_prob = lr.predict_proba(X_test_dtm)[:,1]
y_pred_prob

array([0.00568202, 0.03218058, 0.00474523, ..., 0.00343328, 0.00223177,
       0.0009778 ])

In [34]:
metrics.roc_auc_score(y_test,y_pred_prob)

0.9886661645538608